version: '3'
services:

  devcontainer:
    build: 
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      
      # Sirve para la torre en casa
      - "C:/Users/alfon/OneDrive-UAM-Prof/OneDrive - UAM/Cursos Python/microcredencial-carteras-python-2023:/workspace:cached"

      # Sirve para lenovo universidad
      #- "C:/Users/alfon/OneDrive - UAM/Cursos Python/microcredencial-carteras-python-2023:/workspace:cached"
    
    ports:
      - "8888:8888"
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - PYTHONPATH=/workspace